name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@main
        with:
          otp-version: "25.3"
          elixir-version: "1.14.4"
          version-type: "strict"

      - uses: actions/cache@v3
        with:
          path: _build
          key: mix-build-${{ github.sha }}
          restore-keys: |
            mix-build-

      - run: mix compile

